import Book from './book';

const books: Array<Book> = [
    { id:  1, identifier: 'GEN', name: 'Genesis'         },
    { id:  2, identifier: 'EXO', name: 'Exodus'          },
    { id:  3, identifier: 'LEV', name: 'Leviticus'       },
    { id:  4, identifier: 'NUM', name: 'Numbers'         },
    { id:  5, identifier: 'DEU', name: 'Deuteronomy'     },
    { id:  6, identifier: 'JOS', name: 'Joshua'          },
    { id:  7, identifier: 'JDG', name: 'Judges'          },
    { id:  8, identifier: 'RUT', name: 'Ruth'            },
    { id:  9, identifier: '1SA', name: '1 Samuel'        },
    { id: 10, identifier: '2SA', name: '2 Samuel'        },
    { id: 11, identifier: '1KI', name: '1 Kings'         },
    { id: 12, identifier: '2KI', name: '2 Kings'         },
    { id: 13, identifier: '1CH', name: '1 Chronicles'    },
    { id: 14, identifier: '2CH', name: '2 Chronicles'    },
    { id: 15, identifier: 'EZR', name: 'Ezra'            },
    { id: 16, identifier: 'NEH', name: 'Nehemiah'        },
    { id: 17, identifier: 'EST', name: 'Esther'          },
    { id: 18, identifier: 'JOB', name: 'Job'             },
    { id: 19, identifier: 'PSA', name: 'Psalms'          },
    { id: 20, identifier: 'PRO', name: 'Proverbs'        },
    { id: 21, identifier: 'ECC', name: 'Ecclesiastes'    },
    { id: 22, identifier: 'SNG', name: 'Song of Songs'   },
    { id: 23, identifier: 'ISA', name: 'Isaiah'          },
    { id: 24, identifier: 'JER', name: 'Jeremiah'        },
    { id: 25, identifier: 'LAM', name: 'Lamentations'    },
    { id: 26, identifier: 'EZK', name: 'Ezekiel'         },
    { id: 27, identifier: 'DAN', name: 'Daniel'          },
    { id: 28, identifier: 'HOS', name: 'Hosea'           },
    { id: 29, identifier: 'JOL', name: 'Joel'            },
    { id: 30, identifier: 'AMO', name: 'Amos'            },
    { id: 31, identifier: 'OBA', name: 'Obadiah'         },
    { id: 32, identifier: 'JON', name: 'Jonah'           },
    { id: 33, identifier: 'MIC', name: 'Micah'           },
    { id: 34, identifier: 'NAM', name: 'Nahum'           },
    { id: 35, identifier: 'HAB', name: 'Habakkuk'        },
    { id: 36, identifier: 'ZEP', name: 'Zephaniah'       },
    { id: 37, identifier: 'HAG', name: 'Haggai'          },
    { id: 38, identifier: 'ZEC', name: 'Zechariah'       },
    { id: 39, identifier: 'MAL', name: 'Malachi'         },
    { id: 41, identifier: 'MAT', name: 'Matthew'         },
    { id: 42, identifier: 'MRK', name: 'Mark'            },
    { id: 43, identifier: 'LUK', name: 'Luke'            },
    { id: 44, identifier: 'JHN', name: 'John'            },
    { id: 45, identifier: 'ACT', name: 'Acts'            },
    { id: 46, identifier: 'ROM', name: 'Romans'          },
    { id: 47, identifier: '1CO', name: '1 Corinthians'   },
    { id: 48, identifier: '2CO', name: '2 Corinthians'   },
    { id: 49, identifier: 'GAL', name: 'Galatians'       },
    { id: 50, identifier: 'EPH', name: 'Ephesians'       },
    { id: 51, identifier: 'PHP', name: 'Philippians'     },
    { id: 52, identifier: 'COL', name: 'Colossians'      },
    { id: 53, identifier: '1TH', name: '1 Thessalonians' },
    { id: 54, identifier: '2TH', name: '2 Thessalonians' },
    { id: 55, identifier: '1TI', name: '1 Timothy'       },
    { id: 56, identifier: '2TI', name: '2 Timothy'       },
    { id: 57, identifier: 'TIT', name: 'Titus'           },
    { id: 58, identifier: 'PHM', name: 'Philemon'        },
    { id: 59, identifier: 'HEB', name: 'Hebrews'         },
    { id: 60, identifier: 'JAS', name: 'James'           },
    { id: 61, identifier: '1PE', name: '1 Peter'         },
    { id: 62, identifier: '2PE', name: '2 Peter'         },
    { id: 63, identifier: '1JN', name: '1 John'          },
    { id: 64, identifier: '2JN', name: '2 John'          },
    { id: 65, identifier: '3JN', name: '3 John'          },
    { id: 66, identifier: 'JUD', name: 'Jude'            },
    { id: 67, identifier: 'REV', name: 'Revelation'      }
];

export default books;
